<html>
<head>
<title>TestNG:  Test 1</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Test 1</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>16/5/0</td>
</tr><tr>
<td>Started on:</td><td>Tue Dec 10 16:36:33 IST 2019</td>
</tr>
<tr><td>Total time:</td><td>22 seconds (22721 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testNG.demosoftassert.test1()'><b>test1</b><br>Test class: testNG.demosoftassert</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	expected [Hi] but found [Hello],
	Error message:  both are equal
	at testNG.demosoftassert.test1(demosoftassert.java:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1480465419", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1480465419'><pre>java.lang.AssertionError: The following asserts failed:
	expected [Hi] but found [Hello],
	Error message:  both are equal
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testNG.demosoftassert.test1(demosoftassert.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre></div></td>
<td>0</td>
<td>testNG.demosoftassert@3ffc5af1</td></tr>
<tr>
<td title='testNG.demoassertion.test2()'><b>test2</b><br>Test class: testNG.demoassertion</td>
<td><div><pre>java.lang.AssertionError: Error msg- 20 is greater than 18 expected [false] but found [true]
	at testNG.demoassertion.test2(demoassertion.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1037675582", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1037675582'><pre>java.lang.AssertionError: Error msg- 20 is greater than 18 expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at testNG.demoassertion.test2(demoassertion.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre></div></td>
<td>0</td>
<td>testNG.demoassertion@61832929</td></tr>
<tr>
<td title='testNG.demoassertion.test4()'><b>test4</b><br>Test class: testNG.demoassertion</td>
<td><div><pre>java.lang.AssertionError: expected [Hi] but found [Hello]
	at testNG.demoassertion.test4(demoassertion.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace73508491", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace73508491'><pre>java.lang.AssertionError: expected [Hi] but found [Hello]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at testNG.demoassertion.test4(demoassertion.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre></div></td>
<td>0</td>
<td>testNG.demoassertion@61832929</td></tr>
<tr>
<td title='testNG.demoassertion.test7()'><b>test7</b><br>Test class: testNG.demoassertion</td>
<td><div><pre>java.lang.AssertionError: expected object to not be null
	at testNG.demoassertion.test7(demoassertion.java:40)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace349266500", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace349266500'><pre>java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.assertNotNull(Assert.java:423)
	at org.testng.Assert.assertNotNull(Assert.java:408)
	at testNG.demoassertion.test7(demoassertion.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre></div></td>
<td>0</td>
<td>testNG.demoassertion@61832929</td></tr>
<tr>
<td title='testNG.demoassertion.test8()'><b>test8</b><br>Test class: testNG.demoassertion</td>
<td><div><pre>java.lang.AssertionError: Intentionally failing the condition
	at testNG.demoassertion.test8(demoassertion.java:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1820475135", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1820475135'><pre>java.lang.AssertionError: Intentionally failing the condition
	at org.testng.Assert.fail(Assert.java:94)
	at testNG.demoassertion.test8(demoassertion.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre></div></td>
<td>0</td>
<td>testNG.demoassertion@61832929</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testNG.Mercuryapplication.Login()'><b>Login</b><br>Test class: testNG.Mercuryapplication</td>
<td></td>
<td>0</td>
<td>testNG.Mercuryapplication@5e5792a0</td></tr>
<tr>
<td title='testNG.Mercuryapplication.bookFlight()'><b>bookFlight</b><br>Test class: testNG.Mercuryapplication</td>
<td></td>
<td>0</td>
<td>testNG.Mercuryapplication@5e5792a0</td></tr>
<tr>
<td title='testNG.Mercuryapplication.closeBrowser()'><b>closeBrowser</b><br>Test class: testNG.Mercuryapplication</td>
<td></td>
<td>0</td>
<td>testNG.Mercuryapplication@5e5792a0</td></tr>
<tr>
<td title='testNG.demodataprovider.f()'><b>f</b><br>Test class: testNG.demodataprovider<br>Parameters: lalitha, password123</td>
<td></td>
<td>0</td>
<td>testNG.demodataprovider@29774679</td></tr>
<tr>
<td title='testNG.demodataprovider.f()'><b>f</b><br>Test class: testNG.demodataprovider<br>Parameters: niki, dude</td>
<td></td>
<td>0</td>
<td>testNG.demodataprovider@29774679</td></tr>
<tr>
<td title='testNG.demodataprovider.f()'><b>f</b><br>Test class: testNG.demodataprovider<br>Parameters: Pratik, rana</td>
<td></td>
<td>0</td>
<td>testNG.demodataprovider@29774679</td></tr>
<tr>
<td title='testNG.executionsequence.f()'><b>f</b><br>Test class: testNG.executionsequence</td>
<td></td>
<td>0</td>
<td>testNG.executionsequence@523884b2</td></tr>
<tr>
<td title='testNG.LoginMercury.f()'><b>f</b><br>Test class: testNG.LoginMercury</td>
<td></td>
<td>6</td>
<td>testNG.LoginMercury@5b275dab</td></tr>
<tr>
<td title='testNG.NewTest.f()'><b>f</b><br>Test class: testNG.NewTest</td>
<td></td>
<td>0</td>
<td>testNG.NewTest@26653222</td></tr>
<tr>
<td title='testNG.Mercuryapplication.openBrowser()'><b>openBrowser</b><br>Test class: testNG.Mercuryapplication</td>
<td></td>
<td>0</td>
<td>testNG.Mercuryapplication@5e5792a0</td></tr>
<tr>
<td title='testNG.Mercuryapplication.openURL()'><b>openURL</b><br>Test class: testNG.Mercuryapplication</td>
<td></td>
<td>0</td>
<td>testNG.Mercuryapplication@5e5792a0</td></tr>
<tr>
<td title='testNG.Mercuryapplication.searchFlight()'><b>searchFlight</b><br>Test class: testNG.Mercuryapplication</td>
<td></td>
<td>0</td>
<td>testNG.Mercuryapplication@5e5792a0</td></tr>
<tr>
<td title='testNG.demoassertion.test1()'><b>test1</b><br>Test class: testNG.demoassertion</td>
<td></td>
<td>0</td>
<td>testNG.demoassertion@61832929</td></tr>
<tr>
<td title='testNG.demoassertion.test3()'><b>test3</b><br>Test class: testNG.demoassertion</td>
<td></td>
<td>0</td>
<td>testNG.demoassertion@61832929</td></tr>
<tr>
<td title='testNG.demoassertion.test5()'><b>test5</b><br>Test class: testNG.demoassertion</td>
<td></td>
<td>0</td>
<td>testNG.demoassertion@61832929</td></tr>
<tr>
<td title='testNG.demoassertion.test6()'><b>test6</b><br>Test class: testNG.demoassertion</td>
<td></td>
<td>0</td>
<td>testNG.demoassertion@61832929</td></tr>
</table><p>
</body>
</html>